### PR TITLE
Post Internship Student review #9

### PR DESCRIPTION
**Pull request by richarddushime**
According to the issue #9  this is how i understood the Task and i m requesting for a review and comments 
i created a button on view student page  for **Give feedback **
screencapture-127-0-0-1-5000-view-399-2023-06-29-14_41_20

 when  the button is clicked the standardized vocabulary appears in a form where  changes can be done  and submission 
screencapture-127-0-0-1-5000-feedback-399-2023-06-29-14_41_03

then all the students will be displayed with different feedback 
screencapture-127-0-0-1-5000-feedback-table-399-2023-06-29-14_42_59

i m reallly not sure if its the right way  of things 
but i will be waiting for your feedback

### CODE REVIEW

**Comment by rowlandm** [comment]
Hi Richard,

Thanks for doing this.

I think there has been a miscommunication.

If you look at the Google spreadsheet, you will see that there are drop down options for each attribute.

These attributes then are aggregated to a summary.

Go to the  spreadsheet, to the first tab with David, and change him from"highly adaptable" to "reasonably adaptable".

Audi check out the tab "Standardised Vocabulary" to see all the options for each attribute.

That should help your understanding.

Remember the first rule of coding is "Never write code into you have a strong understanding of the problem you want to solve".

**Comment by rowlandm** [comment]
With that in mind, I think you will need to mainly change the feedback.html file.

**Comment by rowlandm** [comment]
Nice work!

**Comment by richarddushime** [comment]
> Hi Richard,
> 
> Thanks for doing this.
> 
> I think there has been a miscommunication.
> If you look at the Google spreadsheet, you will see that there are drop down options for each attribute.
> 
> These attributes then are aggregated to a summary.
> 
> Go to the spreadsheet, to the first tab with David, and change him from"highly adaptable" to "reasonably adaptable".
> 
> Audi check out the tab "Standardised Vocabulary" to see all the options for each attribute.
> 
> That should help your understanding.
> 
> Remember the first rule of coding is "Never write code into you have a strong understanding of the problem you want to solve".

the fact is All the above details i had not yet observed them , just seen the spreadsheet functionnalities now 
let me  make changes 
and 
Thanks for Quote 🥇 **_"Never write code until you have a strong understanding of the problem you want to solve"_** 👍

**Comment by richarddushime** [comment]
i made a commit with some changes 
about content and design  i will change i want to confirm if its the way before i continue  
Attached screeenschot
screencapture-127-0-0-1-5000-feedback-399-2023-06-30-23_23_37

**Comment by rowlandm** [comment]
I think you are on the right track.

I would say there is another div that you need to show the total combined
choices you have made as a summary.

eg.

Full name 2 is highly adaptive. Full Name 2 is highly collaborative.

This should be before the submit button. Probably needs javascript.

Regards,

*Rowland Mosbergen*
Strategic Leadership | Change Management | Diversity & Inclusion
B of Eng (Aerospace Avionics)
Mob: 0423 030 626
Email: ***@***.***
Web: https://www.practicaldiversity.org

**Comment by richarddushime** [comment]
Hi @rowlandm 
Based on the requested changes i worked on issue #9 
changes are in the last commit 
Here are  screenshots 
Feedback Form

Here after selecting feedbacks  with Review Overal 
Feedback and Review Overal

Data In standardized Vocabulary 
Standardized Vocabulary

Requesting for a Review 
Thank you

**Comment by rowlandm** [comment]
Looking good!

You would just need to change he/him and split them to be pronoun and pronoun2 as in the excel spreadsheet.

eg. 

"David is highly adaptable, as **he** could change the direction of the project easily when he was given new information. David learns technical concepts in a reasonable time, as he could understand high level technical concepts and research how to implement them with some prompting. David could benefit from learning domain concepts and using them to he advantage, as he needed help to use these concepts when communicating, and needed help to use them to guide him when looking at low-level technical problems. David is collaborative as he worked well with other students when prompted. David has a high tolerance for ambiguity, as he handled the lack of clarity of the project and was comfortable in helping to clarify what needed doing. David has a reasonable tolerance for complexity, as he handled the complexity of the project with some support and was comfortable in working at that level with prompting.

David was extremely impressive and I would highly recommend him and I would hire **him** if possible. It is my opinion that he could be placed in an elite team and quickly contribute and continue to improve."

**Comment by rowlandm** [comment]
An extra thing to think about is what if someone half finishes the review and saves it. Will they be able to start from the where they half-finished?

**Comment by richarddushime** [comment]
> Looking good!
> 
> You would just need to change he/him and split them to be pronoun and pronoun2 as in the excel spreadsheet.
> 
> eg.
> 
> "David is highly adaptable, as **he** could change the direction of the project easily when he was given new information. David learns technical concepts in a reasonable time, as he could understand high level technical concepts and research how to implement them with some prompting. David could benefit from learning domain concepts and using them to he advantage, as he needed help to use these concepts when communicating, and needed help to use them to guide him when looking at low-level technical problems. David is collaborative as he worked well with other students when prompted. David has a high tolerance for ambiguity, as he handled the lack of clarity of the project and was comfortable in helping to clarify what needed doing. David has a reasonable tolerance for complexity, as he handled the complexity of the project with some support and was comfortable in working at that level with prompting.
> 
> David was extremely impressive and I would highly recommend him and I would hire **him** if possible. It is my opinion that he could be placed in an elite team and quickly contribute and continue to improve."

Since the Data  or a student can be updated to specify if is he or him then directly  it will be displayed like above as  you suggested , for eg: i m from editing the above students and i gave him david as a name and he , since he is a boy 
while giving feedback directly data was updated 
here is a screenshot 
David

**Comment by richarddushime** [comment]
> 
> An extra thing to think about is what if someone half finishes the review and saves it. Will they be able to start from the where they half-finished?

well as of now its not possible 
 If we want to implement a feature where users can save their review progress and resume from where they left off, we would need to consider user authentication. By requiring users to create accounts and log in, and then we can associate their review session with their account.
Alternatively, we can provide an option for users to save their progress using their email address. This way, they can receive a unique link or code via email that allows them to access their saved session.

**Comment by rowlandm** [comment]
I think you missed my points from the original review - you need both he/him and she/her and they/them

Generic form for the overall external comment:

[name] was extremely impressive and I would highly recommend [pronoun2] and I would hire [pronoun2] if possible. It is my opinion that [pronoun] could be placed in an elite team and quickly contribute and continue to improve.

If David was he/him then
he would be pronoun
him would be pronoun 2

_**David**_ was extremely impressive and I would highly recommend **_him_** and I would hire **_him_** if possible. It is my opinion that **_he_** could be placed in an elite team and quickly contribute and continue to improve.


If Jane was she/her then
she would be pronoun
her would be pronoun 2

_**Jane**_ was extremely impressive and I would highly recommend **_her_** and I would hire **_her_** if possible. It is my opinion that **_she_** could be placed in an elite team and quickly contribute and continue to improve.

**Comment by rowlandm** [comment]
> > An extra thing to think about is what if someone half finishes the review and saves it. Will they be able to start from the where they half-finished?
> 
> well as of now its not possible If we want to implement a feature where users can save their review progress and resume from where they left off, we would need to consider user authentication. By requiring users to create accounts and log in, and then we can associate their review session with their account. Alternatively, we can provide an option for users to save their progress using their email address. This way, they can receive a unique link or code via email that allows them to access their saved session.

As for this - think of it another way. 

1. I go and do a full review of this student and save it.
2. I go back to change the review for one section - say the adaptability section. Will I have to redo the who review? At the moment I have to redo the whole review.

**Comment by richarddushime** [comment]
Hello @rowlandm 
i worked on the changes but i added pronoun3  because there may be a case where  his or their may be needed   as of now its pending and not used anywhere only that i declared it in the function 

about save the progress i added a button  where if you dont finish you can just  click on save progress and later when back you will find all details as left

**Comment by rowlandm** [comment]
If prefer to just you split he/him , she/her, they/them or abc/xyz or any other combination using "/" into pronoun and pronoun2.

So in the table "Students" there is a field "pronouns" that we can use.

No need for the third pronoun.

**Comment by richarddushime** [comment]
> If prefer to just you split he/him , she/her, they/them or abc/xyz or any other combination using "/" into pronoun and pronoun2.
> 
> So in the table "Students" there is a field "pronouns" that we can use.
> 
> No need for the third pronoun.

i have just made a commit for this, i removed the 3rd pronoun since its not needed 
waiting for review or any other comment 
Thank you

**Comment by richarddushime** [comment]
> Hi Richard,
> 
> I think we may have to have a chat as I think you aren't understanding what I'm trying to say.
> 
> It might be worthwhile for you to do some tests as well - as it seems like you have lots of enthusiasm but don't really know why you are doing it.
> 
> You are so close and yet so far and I don't want you wasting your time writing code when we are not thinking the same result :)

sure sure that will be better 
am available today

**Pull request closed without merging**
