### PR TITLE
Opens new tab for email acknowledgement button with the new acknowledgement message.

### PR DESCRIPTION
**Pull request by labib08**
Also added "email acknowledgement" button and "send email to myself" button under new intake all

### CODE REVIEW

**Review by Xenotion — APPROVED** [review]
Looks good to me!

**Comment by rowlandm** [comment]
Sorry - the email acknowledgement is now too long :(

Screen Shot 2024-01-25 at 9 51 02 pm

Can we change the email acknowledgement to be this:

_Hi All,

I will be calling you by mobile phone over the next week to get a better understanding of projects that fit your interests and career aspirations. Please let me know if you need to make other arrangements as I can be flexible.

If I am calling and it is a bad time, don’t answer. I can leave a message and call back later.

To find out more, please read the full email: https://wehi-researchcomputing.github.io/email_acknowledgement_

**Comment by rowlandm** [comment]
Everything else looks great!

**Comment by Xenotion** [comment]
Looks like seperate PR will be made for the new edit. You can merge this one @rowlandm

**Pull request closed without merging**
