### PR TITLE
fake data added

### PR DESCRIPTION
**Pull request by ZIYUT**
129 fake data added for future testing.

### CODE REVIEW

**Comment by rowlandm** [comment]
Did one of these break the assign project page?

**Comment by rowlandm** [comment]
Are you sure you didn't delete the WEHI email branch? It looks like "Copy to WEHI email" is being removed. @Xenotion - could you check the code and test it please?

**Comment by Xenotion** [comment]
We shouldn't be touching any of the files/folders like 
.DS_Store
.idea

**Comment by Xenotion** [comment]
Declining PR as it brings back to old version of code, please merge the latest changes and branch out to make new changes

**Pull request closed without merging**
