### PR TITLE
Shortened the email acknowledgement message

### PR DESCRIPTION
**Pull request by labib08**
Apologies for creating another branch for it

### CODE REVIEW

**Review by Xenotion — APPROVED** [review]
Looks good to me

**Comment by rowlandm** [comment]
This has a trailing _ eg.

https://wehi-researchcomputing.github.io/email_acknowledgement_

instead of

https://wehi-researchcomputing.github.io/email_acknowledgement


Could you change it please? Then it will be good to go.

PS. It is always good to test links in emails before you submit PRs just in case I made a mistake in the URL.

**Comment by labib08** [comment]
Fixed the error in the link and also added the 'email acknowledgement' and 'send email to myself' buttons under new intakes in this branch. So you can merge this branch

**Comment by rowlandm** [comment]
The URL isn't accurate: 

https://wehi-researchcomputing.github.io/email_acknowledgement_

**Comment by rowlandm** [comment]
I needed to do a git pull for the lastest update. Sorry about that.

**Review by rowlandm — APPROVED** [review]
All good.

**Pull request merged**
