### PR TITLE
dashboard breakdown stats

### PR DESCRIPTION
**Pull request by richarddushime**
#3  issue 
requesting for a review
 according to what i did   if a status is changed the dashboard is updated automatically , 
i would suggest of working again on if someone clicks on a certain status  it should display  only  students having that same status

### CODE REVIEW

**Comment by rowlandm** [comment]
Sorry Richard, but there has been a miscommunication. 

It is using status instead of the correct field pronouns.

Th e way the query is being run is also inefficient, a simple query is "Select count(*), pronouns from Students group by pronouns;". You specified each status which is inefficient.

It also deleted all the code that was previously in the dashboard.

I'm going to cancel this and what we can do is to chat on issue#3 so we are on the same page before you do any more work.

Thanks for your enthusiasm! This way we can make you a more efficient programmer.

**Comment by richarddushime** [comment]
> Sorry Richard, but there has been a miscommunication.
> 
> It is using status instead of the correct field pronouns.
> 
> Th e way the query is being run is also inefficient, a simple query is "Select count(*), pronouns from Students group by pronouns;". You specified each status which is inefficient.
> 
> It also deleted all the code that was previously in the dashboard.
> 
> I'm going to cancel this and what we can do is to chat on issue#3 so we are on the same page before you do any more work.
> 
> Thanks for your enthusiasm! This way we can make you a more efficient programmer.

i have just made a different PR 
On My dashboard  there was not any data displayed  may be thats why i never understood  well the task

**Comment by rowlandm** [comment]
Cool, let's close this PR then.

**Comment by richarddushime** [comment]
> Cool, let's close this PR then.

yes let me do so diectly

**Pull request closed without merging**
